import {useEffect,useState} from "react";

export type CaptureType="Note"|"Story"|"Question"|"Link"|"Observation"|"Customer insight";
export interface Capture{id:string;type:CaptureType;text:string;createdAt:number;status:"unprocessed"|"processed"}
export interface LibraryItem{id:string;captureId?:string;type:CaptureType;title:string;body:string;tags:string[];favourite:boolean;archived:boolean;createdAt:number}
export type DraftStatus="idea"|"outline"|"drafting"|"review"|"ready"|"published";
export interface Draft{id:string;title:string;body:string;format:string;platform:string;status:DraftStatus;sourceIds:string[];updatedAt:number;scheduledFor?:string}
export interface ChatMessage{id:string;role:"user"|"assistant";content:string;sourceIds:string[];createdAt:number}
export interface WorkspaceData{captures:Capture[];library:LibraryItem[];drafts:Draft[];messages:ChatMessage[]}
const empty:WorkspaceData={captures:[],library:[],drafts:[],messages:[]};
const id=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const titleFor=(text:string)=>text.trim().split(/[.!?\n]/)[0].slice(0,80)||"Untitled capture";
const tagsFor=(text:string)=>[...new Set((text.toLowerCase().match(/[a-z][a-z-]{4,}/g)??[]).filter((word)=>!new Set(["about","their","there","which","would","could","should"]).has(word)))].slice(0,3);

export function useWorkspaceData(ownerKey:string){const key=`suchamojo:workspace:v1:${ownerKey}`;const [data,setData]=useState<WorkspaceData>(()=>{try{return {...empty,...JSON.parse(localStorage.getItem(key)??"{}")}}catch{return empty}});useEffect(()=>localStorage.setItem(key,JSON.stringify(data)),[data,key]);return {data,
 addCapture:(type:CaptureType,text:string)=>{const capture:Capture={id:id(),type,text,createdAt:Date.now(),status:"unprocessed"};setData((current)=>({...current,captures:[capture,...current.captures]}));return capture.id},
 processCapture:(captureId:string)=>setData((current)=>{const capture=current.captures.find((item)=>item.id===captureId);if(!capture)return current;const item:LibraryItem={id:id(),captureId,type:capture.type,title:titleFor(capture.text),body:capture.text,tags:tagsFor(capture.text),favourite:false,archived:false,createdAt:Date.now()};return {...current,captures:current.captures.map((entry)=>entry.id===captureId?{...entry,status:"processed"}:entry),library:[item,...current.library]}}),
 toggleFavourite:(itemId:string)=>setData((current)=>({...current,library:current.library.map((item)=>item.id===itemId?{...item,favourite:!item.favourite}:item)})),
 archiveItem:(itemId:string)=>setData((current)=>({...current,library:current.library.map((item)=>item.id===itemId?{...item,archived:true}:item)})),
 saveDraft:(draft:Partial<Draft>&{id?:string})=>{const draftId=draft.id??id();setData((current)=>{const existing=current.drafts.find((item)=>item.id===draftId);const next:Draft={id:draftId,title:draft.title??existing?.title??"Untitled draft",body:draft.body??existing?.body??"",format:draft.format??existing?.format??"LinkedIn post",platform:draft.platform??existing?.platform??"LinkedIn",status:draft.status??existing?.status??"idea",sourceIds:draft.sourceIds??existing?.sourceIds??[],updatedAt:Date.now(),scheduledFor:draft.scheduledFor??existing?.scheduledFor};return {...current,drafts:existing?current.drafts.map((item)=>item.id===draftId?next:item):[next,...current.drafts]}});return draftId},
 scheduleDraft:(draftId:string,date:string)=>setData((current)=>({...current,drafts:current.drafts.map((draft)=>draft.id===draftId?{...draft,scheduledFor:date,updatedAt:Date.now()}:draft)})),
 addChat:(content:string)=>setData((current)=>{const sources=current.library.filter((item)=>!item.archived).slice(0,3);const user:ChatMessage={id:id(),role:"user",content,sourceIds:[],createdAt:Date.now()};const answer=sources.length?`Three useful directions from your material: tell the specific moment behind “${sources[0].title}”; challenge the common assumption inside it; or turn it into a practical walkthrough for your audience.`:"Capture or process at least one piece of material first. I won’t invent a personal story that you haven’t given me.";const assistant:ChatMessage={id:id(),role:"assistant",content:answer,sourceIds:sources.map((source)=>source.id),createdAt:Date.now()+1};return {...current,messages:[...current.messages,user,assistant]}}),
 clear:()=>{setData(empty);localStorage.removeItem(key)},
 importDemo:()=>setData({captures:[{id:"demo-c1",type:"Observation",text:"People understand difficult technology faster when they can see one practical use.",createdAt:Date.now(),status:"unprocessed"}],library:[{id:"demo-l1",type:"Story",title:"Engineer to AI educator",body:"I left engineering and learned to teach difficult AI concepts through practical examples.",tags:["teaching","learning","artificial-intelligence"],favourite:true,archived:false,createdAt:Date.now()}],drafts:[{id:"demo-d1",title:"AI should help you think, not think for you",body:"The best AI workflow does not remove your judgement. It gives your judgement better material to work with.",format:"LinkedIn post",platform:"LinkedIn",status:"drafting",sourceIds:["demo-l1"],updatedAt:Date.now()}],messages:[]})}}

