import {getAuthUserId} from "@convex-dev/auth/server";import {v} from "convex/values";import {mutation,query} from "./_generated/server";
const captureType=v.union(v.literal("Note"),v.literal("Story"),v.literal("Question"),v.literal("Link"),v.literal("Observation"),v.literal("Customer insight"));
const draftStatus=v.union(v.literal("idea"),v.literal("outline"),v.literal("drafting"),v.literal("review"),v.literal("ready"),v.literal("published"));
async function userId(ctx:Parameters<typeof getAuthUserId>[0]){const id=await getAuthUserId(ctx);if(!id)throw new Error("You need to sign in first");return id}
const captureDoc=v.object({id:v.id("captures"),type:captureType,text:v.string(),status:v.union(v.literal("unprocessed"),v.literal("processed"),v.literal("archived")),createdAt:v.number()});
const libraryDoc=v.object({id:v.id("libraryItems"),type:captureType,title:v.string(),body:v.string(),tags:v.array(v.string()),favourite:v.boolean(),archived:v.boolean(),createdAt:v.number()});
const draftDoc=v.object({id:v.id("drafts"),title:v.string(),body:v.string(),format:v.string(),platform:v.string(),status:draftStatus,sourceIds:v.array(v.id("libraryItems")),scheduledFor:v.union(v.string(),v.null()),updatedAt:v.number()});
export const snapshot=query({args:{},returns:v.object({captures:v.array(captureDoc),library:v.array(libraryDoc),drafts:v.array(draftDoc)}),handler:async(ctx)=>{const owner=await userId(ctx);const [captures,library,drafts]=await Promise.all([ctx.db.query("captures").withIndex("by_userId_and_createdAt",q=>q.eq("userId",owner)).order("desc").take(200),ctx.db.query("libraryItems").withIndex("by_userId_and_archived",q=>q.eq("userId",owner).eq("archived",false)).take(300),ctx.db.query("drafts").withIndex("by_userId_and_archived",q=>q.eq("userId",owner).eq("archived",false)).take(200)]);const withSources=await Promise.all(drafts.map(async draft=>{const refs=await ctx.db.query("sourceReferences").withIndex("by_draftId",q=>q.eq("draftId",draft._id)).take(50);return {id:draft._id,title:draft.title,body:draft.body,format:draft.format,platform:draft.platform,status:draft.status,sourceIds:refs.filter(ref=>ref.userId===owner).map(ref=>ref.libraryItemId),scheduledFor:draft.scheduledFor??null,updatedAt:draft.updatedAt}}));return {captures:captures.map(item=>({id:item._id,type:item.type,text:item.originalText,status:item.status,createdAt:item.createdAt})),library:library.map(item=>({id:item._id,type:item.type,title:item.title,body:item.body,tags:item.tags,favourite:item.favourite,archived:item.archived,createdAt:item.createdAt})),drafts:withSources}}});
export const capture=mutation({args:{type:captureType,text:v.string()},returns:v.id("captures"),handler:async(ctx,args)=>{const owner=await userId(ctx);const text=args.text.trim();if(!text)throw new Error("Capture cannot be empty");const now=Date.now();return await ctx.db.insert("captures",{userId:owner,type:args.type,originalText:text,status:"unprocessed",createdAt:now,updatedAt:now})}});
export const processCapture=mutation({args:{captureId:v.id("captures")},returns:v.id("libraryItems"),handler:async(ctx,args)=>{const owner=await userId(ctx);const capture=await ctx.db.get(args.captureId);if(!capture||capture.userId!==owner)throw new Error("Capture not found");const existing=await ctx.db.query("libraryItems").withIndex("by_userId_and_archived",q=>q.eq("userId",owner).eq("archived",false)).take(300);const duplicate=existing.find(item=>item.captureId===capture._id);if(duplicate)return duplicate._id;const title=capture.originalText.split(/[.!?\n]/)[0].slice(0,80)||"Untitled capture";const tags=[...new Set(capture.originalText.toLowerCase().match(/[a-z][a-z-]{4,}/g)??[])].slice(0,3);const now=Date.now();const id=await ctx.db.insert("libraryItems",{userId:owner,captureId:capture._id,type:capture.type,title,body:capture.originalText,tags,favourite:false,archived:false,createdAt:now,updatedAt:now});await ctx.db.patch(capture._id,{status:"processed",updatedAt:now});return id}});
export const toggleFavourite=mutation({args:{itemId:v.id("libraryItems")},returns:v.boolean(),handler:async(ctx,args)=>{const owner=await userId(ctx);const item=await ctx.db.get(args.itemId);if(!item||item.userId!==owner)throw new Error("Library item not found");const next=!item.favourite;await ctx.db.patch(item._id,{favourite:next,updatedAt:Date.now()});return next}});
export const archiveLibraryItem=mutation({args:{itemId:v.id("libraryItems")},returns:v.null(),handler:async(ctx,args)=>{const owner=await userId(ctx);const item=await ctx.db.get(args.itemId);if(!item||item.userId!==owner)throw new Error("Library item not found");await ctx.db.patch(item._id,{archived:true,updatedAt:Date.now()});return null}});
export const saveDraft=mutation({args:{draftId:v.optional(v.id("drafts")),title:v.string(),body:v.string(),format:v.string(),platform:v.string(),status:draftStatus,sourceIds:v.array(v.id("libraryItems"))},returns:v.id("drafts"),handler:async(ctx,args)=>{const owner=await userId(ctx);for(const sourceId of args.sourceIds){const source=await ctx.db.get(sourceId);if(!source||source.userId!==owner)throw new Error("Draft source not found")}const now=Date.now();let draftId=args.draftId;if(draftId){const draft=await ctx.db.get(draftId);if(!draft||draft.userId!==owner)throw new Error("Draft not found");await ctx.db.patch(draftId,{title:args.title,body:args.body,format:args.format,platform:args.platform,status:args.status,updatedAt:now})}else draftId=await ctx.db.insert("drafts",{userId:owner,title:args.title,body:args.body,format:args.format,platform:args.platform,status:args.status,archived:false,createdAt:now,updatedAt:now});const refs=await ctx.db.query("sourceReferences").withIndex("by_draftId",q=>q.eq("draftId",draftId!)).take(100);for(const ref of refs)if(ref.userId===owner)await ctx.db.delete(ref._id);for(const sourceId of args.sourceIds)await ctx.db.insert("sourceReferences",{userId:owner,draftId,libraryItemId:sourceId,reason:"Selected by the user for this draft",createdAt:now});return draftId}});
export const scheduleDraft=mutation({args:{draftId:v.id("drafts"),date:v.string()},returns:v.null(),handler:async(ctx,args)=>{const owner=await userId(ctx);const draft=await ctx.db.get(args.draftId);if(!draft||draft.userId!==owner)throw new Error("Draft not found");await ctx.db.patch(draft._id,{scheduledFor:args.date,updatedAt:Date.now()});return null}});
