import {useEffect,useMemo,useRef,useState} from "react";
import type {ContentUniverse} from "../../lib/recommendation";
import {toShareableUniverse} from "../../lib/shareableUniverse";
import {track} from "../../lib/analytics";
import {downloadRenderedCard,renderShareCardPng} from "../../lib/sharePackExport";
import {ShareCardRenderer} from "./StoryCard";
import {buildSharePack,captionFor,shareFormats,shareTemplates,type ShareFormat,type SharePlatform,type ShareTemplate} from "./storyCardData";

type ShareInput=ReturnType<typeof toShareableUniverse>&{includeName:boolean};
const names:Record<ShareTemplate,string>={identity:"Identity",brain:"Brain",yaps:"Yap",territory:"Territory",superpower:"Superpower",insight:"Insight"};
const platforms:SharePlatform[]=["instagram","linkedin","x"];

export function StoryShareStudio({universe,yapTopics=[],initialTemplate="identity",onCreateShare,onNeedAccount,onYap}:{universe:ContentUniverse;yapTopics?:string[];initialTemplate?:ShareTemplate;onCreateShare?:(input:ShareInput)=>Promise<{slug:string}>;onNeedAccount?:()=>void;onYap?:(topic:string)=>void}){
 const [template,setTemplate]=useState<ShareTemplate>(initialTemplate);const [format,setFormat]=useState<ShareFormat>("story");const [platform,setPlatform]=useState<SharePlatform>("instagram");const [shareUrl,setShareUrl]=useState("");const [caption,setCaption]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [shared,setShared]=useState(false);
 const sectionRef=useRef<HTMLElement>(null);const carouselRef=useRef<HTMLDivElement>(null);const exportRef=useRef<HTMLDivElement>(null);const seen=useRef(false);const scrollFrame=useRef(0);const pack=useMemo(()=>buildSharePack(universe,yapTopics),[universe,yapTopics]);const index=shareTemplates.indexOf(template);
 useEffect(()=>setCaption(captionFor(pack,template,platform,"[link]")),[pack,template,platform]);
 useEffect(()=>{const node=sectionRef.current;if(!node||typeof IntersectionObserver==="undefined")return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!seen.current){seen.current=true;track("share_section_viewed",{template,format,platform,shareId:shareUrl.split("/").pop()||null});observer.disconnect()}},{threshold:.4});observer.observe(node);return()=>observer.disconnect()},[format,platform,shareUrl,template]);
 const properties=(extra:Record<string,string|number|boolean|null>={})=>({template,format,platform,shareId:shareUrl.split("/").pop()||null,...extra});
 const chooseTemplate=(next:ShareTemplate)=>{setTemplate(next);track("share_template_selected",{...properties(),template:next});document.querySelector(`[data-share-slide="${next}"]`)?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})};
 const chooseFormat=(next:ShareFormat)=>{setFormat(next);track("share_format_selected",{...properties(),format:next})};
 const move=(amount:number)=>chooseTemplate(shareTemplates[(index+amount+shareTemplates.length)%shareTemplates.length]);
 const syncFromScroll=()=>{cancelAnimationFrame(scrollFrame.current);scrollFrame.current=requestAnimationFrame(()=>{const carousel=carouselRef.current;if(!carousel)return;const center=carousel.getBoundingClientRect().left+carousel.clientWidth/2;const slides=[...carousel.querySelectorAll<HTMLElement>("[data-share-slide]")];const closest=slides.sort((a,b)=>Math.abs(a.getBoundingClientRect().left+a.clientWidth/2-center)-Math.abs(b.getBoundingClientRect().left+b.clientWidth/2-center))[0]?.dataset.shareSlide as ShareTemplate|undefined;if(closest&&closest!==template)setTemplate(closest)})};
 const ensureShareUrl=async()=>{if(shareUrl)return shareUrl;if(!onCreateShare){onNeedAccount?.();throw new Error("Create an account to make a public share link.")}const {slug}=await onCreateShare({...toShareableUniverse(universe),includeName:false});const url=new URL(`/u/${slug}`,location.origin).href;setShareUrl(url);track("universe_share_link_created",{referral_share_id:slug});return url};
 const renderActive=async()=>{const node=exportRef.current?.querySelector<HTMLElement>(`[data-export-template="${template}"] [data-share-card]`);if(!node)throw new Error("Card preview is not ready.");return renderShareCardPng(node,format,`content-universe-${index+1}-${template}-${format}.png`)};
 const download=async()=>{setBusy(true);setNotice("");try{const result=await renderActive();downloadRenderedCard(result.dataUrl,result.file.name);track("share_downloaded",properties());setNotice(`${shareFormats[format].label} card downloaded.`);setShared(true)}catch{setNotice("The image could not be made yet. Try again.")}finally{setBusy(false)}};
 const downloadSet=async()=>{setBusy(true);setNotice("");try{for(const [cardIndex,item] of shareTemplates.entries()){const node=exportRef.current?.querySelector<HTMLElement>(`[data-export-template="${item}"] [data-share-card]`);if(!node)continue;const filename=`content-universe-${String(cardIndex+1).padStart(2,"0")}-${item}-${format}.png`;const result=await renderShareCardPng(node,format,filename);downloadRenderedCard(result.dataUrl,filename)}track("share_downloaded",properties({template:"all"}));setNotice("All six cards downloaded.");setShared(true)}catch{setNotice("The complete set could not be made yet. Try again.")}finally{setBusy(false)}};
 const shareSet=async()=>{setBusy(true);setNotice("");try{const url=await ensureShareUrl();const files:File[]=[];for(const [cardIndex,item] of shareTemplates.entries()){const node=exportRef.current?.querySelector<HTMLElement>(`[data-export-template="${item}"] [data-share-card]`);if(!node)continue;const filename=`content-universe-${String(cardIndex+1).padStart(2,"0")}-${item}-${format}.png`;files.push((await renderShareCardPng(node,format,filename)).file)}if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){track("share_native_opened",properties({template:"all",shareId:url.split("/").pop()||null}));await navigator.share({title:"My Content Universe",text:`My Content Universe: ${pack.archetype}`,url,files})}else{for(const file of files){const dataUrl=URL.createObjectURL(file);downloadRenderedCard(dataUrl,file.name);setTimeout(()=>URL.revokeObjectURL(dataUrl),1000)}await navigator.clipboard.writeText(url);setNotice("All six cards downloaded and public link copied.")}setShared(true)}catch(error){if((error as Error).name!=="AbortError")setNotice((error as Error).message||"The complete set could not be shared.")}finally{setBusy(false)}};
 const nativeShare=async()=>{setBusy(true);setNotice("");try{const url=await ensureShareUrl();const result=await renderActive();const text=caption.replace("[link]",url);if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[result.file]}))){track("share_native_opened",properties({shareId:url.split("/").pop()||null}));await navigator.share({title:`My Content Universe: ${pack.archetype}`,text,url,files:[result.file]})}else{downloadRenderedCard(result.dataUrl,result.file.name);await navigator.clipboard.writeText(url);setNotice("Image downloaded and public link copied.")}setShared(true)}catch(error){if((error as Error).name!=="AbortError")setNotice((error as Error).message||"Sharing did not finish.")}finally{setBusy(false)}};
 const copyLink=async()=>{try{const url=await ensureShareUrl();await navigator.clipboard.writeText(url);track("share_link_copied",properties({shareId:url.split("/").pop()||null}));setNotice("Public link copied.")}catch(error){setNotice((error as Error).message||"Couldn’t copy the link.")}};
 const copyCaption=async()=>{try{const url=await ensureShareUrl();const text=caption.replace("[link]",url);setCaption(text);await navigator.clipboard.writeText(text);track("share_caption_copied",properties({shareId:url.split("/").pop()||null}));setNotice("Caption copied.")}catch(error){setNotice((error as Error).message||"Couldn’t copy the caption.")}};
 const platformAction=async(next:SharePlatform)=>{try{setPlatform(next);if(next==="instagram"){await nativeShare();return}const url=await ensureShareUrl();const text=captionFor(pack,template,next,url);if(next==="x"){window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text.replace(url,"").trim())}&url=${encodeURIComponent(url)}`,"_blank","noopener,noreferrer");setShared(true);return}if(navigator.share){track("share_native_opened",properties({platform:next,shareId:url.split("/").pop()||null}));await navigator.share({title:`My Content Universe: ${pack.archetype}`,text,url});setShared(true)}else{await navigator.clipboard.writeText(text);setCaption(text);setNotice("LinkedIn caption and link copied.");setShared(true)}}catch(error){if((error as Error).name!=="AbortError")setNotice((error as Error).message||"That share action did not finish.")}};
 const yap=(topic=pack.yapTopics[0])=>{track("yap_from_share_clicked",properties());onYap?.(topic)};
 return <section ref={sectionRef} className="share-pack-studio" onKeyDown={event=>{if(event.key==="ArrowRight")move(1);if(event.key==="ArrowLeft")move(-1)}} tabIndex={0}>
  <header><div><span>SHARE YOUR CONTENT UNIVERSE</span><h2>Pick a card. Post the one that feels most like you.</h2></div><b>{index+1} / 6</b></header>
  <div className="share-format-switcher"><small>FORMAT</small>{(Object.keys(shareFormats) as ShareFormat[]).map(item=><button className={format===item?"is-active":""} onClick={()=>chooseFormat(item)} key={item}>{shareFormats[item].label}</button>)}</div>
  <div ref={carouselRef} className={`share-carousel share-carousel--${format}`} onScroll={syncFromScroll} onWheel={event=>{if(Math.abs(event.deltaY)>Math.abs(event.deltaX)){event.preventDefault();carouselRef.current?.scrollBy({left:event.deltaY,behavior:"smooth"})}}}>{shareTemplates.map(item=><div data-share-slide={item} className={`share-slide ${template===item?"is-active":""}`} key={item} onClick={()=>chooseTemplate(item)}><div className="share-preview-scale"><ShareCardRenderer data={pack} template={item} format={format} interactive={item==="yaps"} onYap={yap}/></div></div>)}</div>
  <div className="share-carousel-nav"><button onClick={()=>move(-1)}>← Previous</button><div>{shareTemplates.map((item,itemIndex)=><button className={template===item?"is-active":""} onClick={()=>chooseTemplate(item)} key={item}><b>{String(itemIndex+1).padStart(2,"0")}</b>{names[item]}</button>)}</div><button onClick={()=>move(1)}>Next →</button></div>
  <div className="share-pack-actions"><button className="is-primary" onClick={()=>void nativeShare()} disabled={busy}>{busy?"Making card…":"Share"}</button><button onClick={()=>void download()} disabled={busy}>Download</button><button onClick={()=>void shareSet()} disabled={busy}>Share set</button><button onClick={()=>void downloadSet()} disabled={busy}>Download set</button><button onClick={()=>void copyLink()}>Copy link</button><button onClick={()=>void copyCaption()}>Copy caption</button></div>
  <div className="share-caption"><header><small>CAPTION</small><div>{platforms.map(item=><button className={platform===item?"is-active":""} onClick={()=>setPlatform(item)} key={item}>{item==="x"?"X":item[0].toUpperCase()+item.slice(1)}</button>)}</div></header><textarea value={caption} onChange={event=>setCaption(event.target.value)} aria-label="Share caption"/><div className="share-platform-actions">{platforms.map(item=><button onClick={()=>void platformAction(item)} key={item}>{item==="instagram"?"Instagram — download / share":item==="linkedin"?"LinkedIn — share / copy":"X — open post"}</button>)}</div></div>
  {notice?<p className="share-pack-notice" role="status">{notice}</p>:null}{shared?<aside className="share-after"><p>Nice. Now make something from it.</p><button onClick={()=>yap()}>WHAT SHOULD I YAP ABOUT? →</button></aside>:null}
  <div ref={exportRef} className="share-export-stage" aria-hidden="true">{shareTemplates.map(item=><div data-export-template={item} key={item}><ShareCardRenderer data={pack} template={item} format={format}/></div>)}</div>
 </section>;
}
