import type {ContentUniverse} from "../../lib/recommendation";

export const creatorTypeNames=["THE IDEA TRANSLATOR","THE STORY-LED CREATOR","THE POINT-OF-VIEW CREATOR","THE CURIOUS EXPLORER","THE TEACHER","THE CONVERSATION CREATOR","THE SYSTEMS CREATOR","THE OPERATOR","THE CONNECTOR","THE TASTE-MAKER"] as const;
export type CreatorTypeName=typeof creatorTypeNames[number];
export interface CreatorTypeResult{creatorType:CreatorTypeName;whyYou:string;whyYouShouldCreate:string;createMore:string[];watchOutFor:string;signatureStrength:string}
export interface CreatorTypeDefinition{name:CreatorTypeName;short:string;accent:string;visual:"translator"|"story"|"pov"|"explorer"|"teacher"|"conversation"|"systems"|"operator"|"connector"|"taste";defaults:Omit<CreatorTypeResult,"creatorType"|"whyYou">}

export const creatorTypeDefinitions:Record<CreatorTypeName,CreatorTypeDefinition>={
 "THE IDEA TRANSLATOR":{name:"THE IDEA TRANSLATOR",short:"Makes complicated things useful.",accent:"#D8F15A",visual:"translator",defaults:{whyYouShouldCreate:"People do not need more information. They need someone who can make it useful.",createMore:["Explainers","Frameworks","Breakdowns","Talking-head videos"],watchOutFor:"Over-explaining before getting to the point.",signatureStrength:"Turning complexity into clarity."}},
 "THE STORY-LED CREATOR":{name:"THE STORY-LED CREATOR",short:"Makes people care through experience.",accent:"#EE3E36",visual:"story",defaults:{whyYouShouldCreate:"People remember the lesson when they can feel the moment that produced it.",createMore:["Personal stories","Scene-led lessons","Origin posts","Narrative videos"],watchOutFor:"Telling the whole story before revealing why it matters.",signatureStrength:"Making useful ideas feel human."}},
 "THE POINT-OF-VIEW CREATOR":{name:"THE POINT-OF-VIEW CREATOR",short:"Says what others leave unsaid.",accent:"#246BFD",visual:"pov",defaults:{whyYouShouldCreate:"Your clearest value is not more facts. It is a view people can react to.",createMore:["Hot takes","Contrarian posts","Belief essays","Commentary videos"],watchOutFor:"Mistaking provocation for a useful argument.",signatureStrength:"Giving familiar topics a sharper angle."}},
 "THE CURIOUS EXPLORER":{name:"THE CURIOUS EXPLORER",short:"Follows questions into useful territory.",accent:"#F47A27",visual:"explorer",defaults:{whyYouShouldCreate:"Your curiosity gives other people permission to explore ideas before they are obvious.",createMore:["Rabbit holes","Field notes","Trend explorations","Learning logs"],watchOutFor:"Starting a new trail before finishing the useful finding.",signatureStrength:"Finding interesting paths others miss."}},
 "THE TEACHER":{name:"THE TEACHER",short:"Helps people understand and act.",accent:"#D5A51D",visual:"teacher",defaults:{whyYouShouldCreate:"What feels obvious to you may be the explanation someone else has been waiting for.",createMore:["How-to posts","Lessons","Visual guides","Step-by-step videos"],watchOutFor:"Teaching the complete syllabus when one lesson would do.",signatureStrength:"Making progress feel possible."}},
 "THE CONVERSATION CREATOR":{name:"THE CONVERSATION CREATOR",short:"Finds ideas by thinking with people.",accent:"#F05AA6",visual:"conversation",defaults:{whyYouShouldCreate:"Your best thinking comes alive when another voice gives it something to push against.",createMore:["Interviews","Q&As","Reaction posts","Live discussions"],watchOutFor:"Waiting for another person before stating your own view.",signatureStrength:"Turning exchange into insight."}},
 "THE SYSTEMS CREATOR":{name:"THE SYSTEMS CREATOR",short:"Turns chaos into a repeatable process.",accent:"#2E9B57",visual:"systems",defaults:{whyYouShouldCreate:"People want to see the process behind the result, not only the polished ending.",createMore:["Workflows","Templates","Process maps","Behind-the-system posts"],watchOutFor:"Perfecting the system longer than the work requires.",signatureStrength:"Making scattered work repeatable."}},
 "THE OPERATOR":{name:"THE OPERATOR",short:"Creates from doing the real work.",accent:"#C99000",visual:"operator",defaults:{whyYouShouldCreate:"Your advantage is proximity to real decisions, trade-offs and consequences.",createMore:["Build logs","Case studies","Decision notes","Practical playbooks"],watchOutFor:"Assuming the lesson is obvious because you lived it.",signatureStrength:"Turning execution into evidence."}},
 "THE CONNECTOR":{name:"THE CONNECTOR",short:"Links people and ideas others keep separate.",accent:"#20C8D8",visual:"connector",defaults:{whyYouShouldCreate:"Your value appears in the relationship between ideas, not in one topic alone.",createMore:["Intersection posts","Introductions","Pattern maps","Cross-industry lessons"],watchOutFor:"Making so many connections that the central point disappears.",signatureStrength:"Seeing the link before everyone else."}},
 "THE TASTE-MAKER":{name:"THE TASTE-MAKER",short:"Chooses what deserves attention.",accent:"#8B5CF6",visual:"taste",defaults:{whyYouShouldCreate:"In a world of endless options, careful selection is a useful creative act.",createMore:["Curated lists","Reviews","Reference breakdowns","What-to-ignore posts"],watchOutFor:"Letting high standards stop you from showing your reasoning.",signatureStrength:"Knowing what is worth keeping."}},
};
export const isCreatorTypeName=(value:unknown):value is CreatorTypeName=>typeof value==="string"&&(creatorTypeNames as readonly string[]).includes(value);
const signals:Record<CreatorTypeName,string[]>={
 "THE IDEA TRANSLATOR":["explain","clarity","clear","complex","translate","simplify","breakdown","understand"],"THE STORY-LED CREATOR":["story","scene","memory","anecdote","moment","narrative","turning"],"THE POINT-OF-VIEW CREATOR":["belief","opinion","contrarian","disagree","point of view","perspective","stance","misconception"],"THE CURIOUS EXPLORER":["curious","learn","explore","rabbit","research","question","emerging","discover"],"THE TEACHER":["teach","guide","lesson","how to","educat","step","help people","framework"],"THE CONVERSATION CREATOR":["conversation","interview","talk","discussion","community","question","podcast","live"],"THE SYSTEMS CREATOR":["system","process","workflow","template","repeatable","organize","structure","framework"],"THE OPERATOR":["build","operate","execute","decision","result","practical","implement","case study"],"THE CONNECTOR":["connect","intersection","network","link","overlap","people","relationship","pattern"],"THE TASTE-MAKER":["taste","curate","select","choose","reference","review","quality","aesthetic"]};
export function classifyCreatorTypeFallback(universe:ContentUniverse):CreatorTypeResult{const primary=JSON.stringify({gifts:universe.gifts,radiance:universe.radiance,expression:universe.expression,povs:universe.povs,expertise:universe.expertise,pillars:universe.contentPillars,proof:universe.opportunities}).toLowerCase();const supporting=JSON.stringify({character:universe.character,stories:universe.storyBank}).toLowerCase();const ranked=creatorTypeNames.map((name,index)=>({name,index,score:signals[name].reduce((score,word)=>score+(primary.split(word).length-1)*3+(supporting.split(word).length-1),0)})).sort((a,b)=>b.score-a.score||a.index-b.index);const creatorType=ranked[0].score?ranked[0].name:"THE IDEA TRANSLATOR";const definition=creatorTypeDefinitions[creatorType];const evidence=universe.gifts.superpower||universe.character.summary;return {creatorType,whyYou:`Your Content Universe repeatedly points to ${definition.short.toLowerCase()} ${evidence}`.replace(/\s+/g," ").slice(0,220),...definition.defaults}}
