import { useMemo, useState } from "react";
import type { UniverseAnswers } from "../../lib/recommendation";
import { track } from "../../lib/analytics";

const screens = [
  { key: "character", label: "01 — CHARACTER", question: "What experiences made you who you are?", helper: "Write the messy version. A few honest lines are enough.", prompts:["Where did you start?","Which career or life shifts shaped you?","What have you built, learned or survived?","Which people or communities changed you?","What do those experiences make you believe now?"], starters:["I started as…","I grew up in…","A turning point was…","Over time, I moved from… to…","That journey taught me…","Today, I see my work as…"], example:"I started as a journalist and mobile storyteller. That taught me to find stories inside ordinary things, ask better questions and explain ideas simply. Over time, I moved into the creator economy, growth and personal branding, working with founders, experts, creators and businesses. I’ve trained thousands of creators, worked on campaigns that reached millions, built communities, consulted founders and built my own business. That journey taught me that content is not just posting. It turns what someone knows, believes and has experienced into something other people can understand and care about.", placeholder: "I started as… A turning point was… That journey taught me…" },
  { key: "gifts", label: "02 — OWN GIFTS", question: "What do people naturally come to you for?", helper: "Think about real requests, not job titles.", prompts:["What do people ask your advice about?","What messy problem can you make clear?","What do you notice that others miss?","What result have you helped people reach?","What feels easy to you but valuable to others?"], starters:["People usually come to me when…","I help people figure out…","I’m unusually good at…","I can listen to someone ramble and…","People leave our conversations with…","The problem I solve best is…"], example:"People come to me when they know they should create content but don’t know what to say, how to position themselves or how to make their ideas interesting. They ask about personal branding, content strategy, storytelling, hooks, formats, creator economy shifts and AI workflows. A lot of what I naturally do is listen to someone ramble, find what is actually interesting, and turn it into a clear content direction and repeatable system.", placeholder: "People usually come to me when… I help them…" },
  { key: "obsessions", label: "03 — RADIANCE", question: "What can you genuinely not shut up about?", helper: "Include the subjects, questions and changes you keep returning to.", prompts:["What rabbit holes do you enter for fun?","Which conversations give you energy?","What do you have a strong point of view about?","What change in your industry fascinates you?","What do you want to create around for years?"], starters:["I can talk endlessly about…","I keep coming back to…","I believe most people get this wrong…","I wish more people understood…","The change I’m watching closely is…","I want to create around the intersection of…"], example:"I keep coming back to the intersection of content, expertise, storytelling, business and AI. I think about why interesting people make boring content, how experts can build a reputation without becoming performative, how creators become businesses, and how AI can become a second brain instead of another writing tool. I want to create around Content Intelligence, Personal Branding, Storytelling, the Creator Economy, AI + Content, Content Systems and what I’m learning while building Suchamojo in public.", placeholder: "I keep coming back to… I want to create around…" },
] as const;
const formats = ["Talking to camera", "Writing", "Teaching", "Storytelling", "Interviews / conversations", "Frameworks", "Workshops", "Breakdowns", "Long-form video", "Short opinion posts"];
const expressionPrompts=["Where do you feel least forced?","How do you make difficult ideas easier?","Do you think best alone or with someone?","Do you prefer examples, stories or frameworks?","Which formats could you sustain every week?"];
const expressionStarters=["I express myself best when…","My natural style is…","I’m strongest when I can…","I sound least forced when…","The formats I could sustain are…","I’m somewhere between a… and a…"];
const shubhamExpressionExample="I feel most natural when I’m talking through an idea, teaching it, or having a real conversation. I’m better when I can explain something with examples and stories rather than sounding scripted or overly polished.";

interface FourRambleFlowProps {
  answers: UniverseAnswers; authenticated: boolean; error?: string; busy?: boolean;
  onBack: () => void; onLogin?: () => void; onChange: (key: string, value: string) => void;
  onSaveStep: (step: number) => Promise<void>; onComplete: () => void | Promise<void>;
}

export function FourRambleFlow({ answers, authenticated, error = "", busy = false, onBack, onLogin, onChange, onSaveStep, onComplete }: FourRambleFlowProps) {
  const firstIncomplete = ["character", "gifts", "obsessions"].findIndex((key) => !(answers[key] ?? "").trim());
  const [step, setStep] = useState(firstIncomplete < 0 ? (answers.expressionFormats ? 3 : 0) : firstIncomplete);
  const [saving, setSaving] = useState(false);
  const [showExample,setShowExample]=useState(false);
  const [showAuthPrompt,setShowAuthPrompt]=useState(false);
  const [authPromptSeen,setAuthPromptSeen]=useState(authenticated);
  const expression = step === 3;
  const screen = screens[Math.min(step, 2)];
  const value = answers[expression ? "expressionNotes" : screen.key] ?? "";
  const selected = useMemo(() => (answers.expressionFormats ?? "").split(" | ").filter(Boolean), [answers.expressionFormats]);
  const invalid = expression ? !selected.length : !value.trim();
  const moveTo=(nextStep:number)=>{setShowExample(false);setStep(nextStep)};
  const addStarter=(starter:string)=>onChange(expression?"expressionNotes":screen.key,`${value}${value.trim()?"\n":""}${starter} `);
  const next = async () => { if (busy || saving) return; setSaving(true); try { await onSaveStep(step); track(`universe_question_${step+1}_completed` as "universe_question_1_completed"|"universe_question_2_completed"|"universe_question_3_completed"|"universe_question_4_completed"); if(step===2&&!authenticated&&!authPromptSeen){setAuthPromptSeen(true);setShowAuthPrompt(true);return}if (step < 3) moveTo(step + 1); else await onComplete(); } catch { /* The parent keeps the user's local answer and shows the save error. */ } finally { setSaving(false); } };
  const openLogin=()=>{sessionStorage.setItem("suchamojo:return-to","/universe/start");onLogin?.()};
  const continueWithoutAccount=()=>{setShowAuthPrompt(false);moveTo(3)};

  return <main className="ramble-flow">
    <header><button type="button" onClick={step ? () => moveTo(step - 1) : onBack} disabled={busy || saving}>← BACK</button><div><span>BUILDING YOUR CONTENT BRAIN</span><strong><span>{String(step + 1).padStart(2, "0")} / 04</span><small>ABOUT {4-step} {4-step===1?"MIN":"MINS"} LEFT</small></strong></div><i>{saving ? "SAVING…" : authenticated ? "SAVED TO ACCOUNT" : "SAVED ON THIS DEVICE"}</i></header>
    <div className="ramble-progress"><i style={{ width: `${(step + 1) * 25}%` }} /></div>
    <section><aside className="ramble-brain" aria-label={`${step} answers added to Content Brain`}><span>CONTENT</span><strong>BRAIN</strong>{Array.from({ length: step }, (_, index) => <i key={index} />)}</aside><article>
      <span>{expression ? "04 — EXPRESSION" : screen.label}</span><h1>{expression ? "How do you naturally express yourself?" : screen.question}</h1><p>{expression ? "Choose what feels easy. You can pick more than one." : screen.helper}</p>
      <div className="ramble-prompts" aria-label="Things to think about">{(expression?expressionPrompts:screen.prompts).map((prompt,index)=><span key={prompt}><b>{index+1}</b>{prompt}</span>)}</div>
      {expression ? <div className="ramble-formats">{formats.map((format) => { const active = selected.includes(format); return <button type="button" aria-pressed={active} className={active ? "is-selected" : ""} onClick={() => onChange("expressionFormats", (active ? selected.filter((item) => item !== format) : [...selected, format]).join(" | "))} key={format}>{format}<b>{active ? "✓" : "+"}</b></button>; })}</div> : null}
      <div className="ramble-starters"><small>NEED A FIRST LINE?</small>{(expression?expressionStarters:screen.starters).map(starter=><button type="button" onClick={()=>addStarter(starter)} key={starter}>{starter} +</button>)}</div>
      <label className="ramble-input"><span>{expression ? "Anything else about your style?" : "Your answer"}</span><textarea autoFocus value={value} onChange={(event) => onChange(expression ? "expressionNotes" : screen.key, event.target.value)} placeholder={expression ? "I feel most natural when..." : screen.placeholder} /></label>
      <div className={`ramble-example ${expression?"is-expression":""} ${showExample?"is-open":""}`}><button type="button" aria-expanded={showExample} onClick={()=>setShowExample(!showExample)}>{expression?(showExample?"HIDE SHUBHAM’S EXAMPLE ↑":"SEE SHUBHAM’S EXAMPLE ↓"):(showExample?"HIDE EXAMPLE ↑":"SEE CAMASOU’S EXAMPLE ↓")}</button>{expression?<div className="ramble-example-reveal" aria-hidden={!showExample}><blockquote><small>SHUBHAM’S EXAMPLE</small><p>“{shubhamExpressionExample}”</p></blockquote></div>:showExample?<blockquote><small>CAMASOU’S CREATOR EXAMPLE · USE FOR SHAPE, NOT WORDS</small><p>{screen.example}</p></blockquote>:null}</div>
      {error ? <p className="ramble-error" role="alert">{error}</p> : null}<footer><button type="button" onClick={() => void next()} disabled={invalid || busy || saving}>{saving ? "SAVING…" : busy ? "BUILDING…" : step === 3 ? "Build my universe →" : "Continue"}</button>{!authenticated && step === 0 ? <button type="button" className="ramble-login" onClick={onLogin}>LOG IN TO SAVE ACROSS DEVICES</button> : null}</footer>
    </article></section>
    {showAuthPrompt?<div className="ramble-auth-prompt" role="dialog" aria-modal="true" aria-labelledby="save-your-brain-title"><section><span>YOUR FIRST THREE ANSWERS ARE SAFE</span><h2 id="save-your-brain-title">Want to keep your brain across devices?</h2><p>Create an account or sign in before the final question. Your Character, Own Gifts and Radiance answers are already saved on this device.</p><div><button type="button" onClick={openLogin}>SIGN IN OR CREATE ACCOUNT →</button><button type="button" onClick={continueWithoutAccount}>CONTINUE WITHOUT AN ACCOUNT</button></div><small>You can still finish and see your Content Universe without signing in.</small></section></div>:null}
  </main>;
}
