import { useState } from "react";
import type { ContentUniverse } from "../../lib/recommendation";
import { toShareableUniverse } from "../../lib/shareableUniverse";
import { track } from "../../lib/analytics";

type ShareInput = ReturnType<typeof toShareableUniverse> & { includeName: boolean };
export function UniverseIdentityArtifact({universe,onCreate,onCreateShare,onNeedAccount}:{universe:ContentUniverse;onCreate?:()=>void;onCreateShare?:(input:ShareInput)=>Promise<{slug:string}>;onNeedAccount?:()=>void}) {
  const identity=toShareableUniverse(universe);
  const [confirmed,setConfirmed]=useState(()=>localStorage.getItem("suchamojo:universe-confirmed")==="true"); const [includeName,setIncludeName]=useState(false); const [shareUrl,setShareUrl]=useState(""); const [notice,setNotice]=useState(""); const [sharing,setSharing]=useState(false);
  const confirm=()=>{if(!confirmed)track("universe_confirmed");localStorage.setItem("suchamojo:universe-confirmed","true");setConfirmed(true)};
  const ensureShareUrl=async()=>{if(shareUrl)return shareUrl;if(!onCreateShare){onNeedAccount?.();throw new Error("Create an account to make a public share link.")}const {slug}=await onCreateShare({...identity,includeName});const url=new URL(`/u/${slug}`,location.origin).href;setShareUrl(url);track("universe_share_link_created",{referral_share_id:slug});return url};
  const share=async()=>{setSharing(true);setNotice("");try{const url=await ensureShareUrl();track("universe_share_clicked",{referral_share_id:url.split("/").pop()??""});if(navigator.share)await navigator.share({title:`My Content Universe: ${identity.archetype}`,text:`Apparently I’m ${identity.archetype}. What’s your Content Universe?`,url});else{await navigator.clipboard.writeText(url);setNotice("LINK COPIED ✓")}}catch(cause){if(cause instanceof Error&&cause.name!=="AbortError")setNotice(cause.message)}finally{setSharing(false)}};
  const copyLink=async()=>{try{const url=await ensureShareUrl();await navigator.clipboard.writeText(url);setNotice("LINK COPIED ✓")}catch(cause){setNotice(cause instanceof Error?cause.message:"Could not copy the link.")}};
  const copyResult=async()=>{await navigator.clipboard.writeText(`${identity.archetype}\n\nSuperpower: ${identity.superpower}\n\nContent territory: ${identity.territory.join(" × ")}\n\nYou could become known for: ${identity.positioning}\n\n${identity.pillars.join(" · ")}\n\nYour brain noticed: ${identity.insight}`);setNotice("RESULT COPIED ✓")};
  const actions=<div className="universe-share-actions"><button className={confirmed?"is-confirmed":""} onClick={confirm}>{confirmed?"LOCKED IN ✓":"THAT’S ME"}</button><button className="universe-share-primary" onClick={()=>void share()} disabled={sharing}>{sharing?"MAKING YOUR LINK…":"SHARE MY UNIVERSE →"}</button><button onClick={()=>void copyLink()}>COPY SHARE LINK</button><button onClick={()=>void copyResult()}>COPY RESULT</button><button onClick={onCreate}>CREATE WITH THIS UNIVERSE →</button><label className="universe-share-name"><input type="checkbox" checked={includeName} onChange={(event)=>{setIncludeName(event.target.checked);setShareUrl("")}}/> Show my first name on the public page</label>{confirmed?<p role="status"><strong>Locked in.</strong> This feels like you? Put it out into the world.</p>:null}{notice?<p role="status">{notice}</p>:null}</div>;
  return <header className="universe-identity-artifact"><div className="universe-identity-kicker"><span>EVERYTHING CONTENT</span><b>MY CONTENT UNIVERSE</b></div><section className="universe-identity-main"><span>ARCHETYPE</span><h1>{identity.archetype}</h1>{actions}<div className="universe-identity-facts"><article><small>SUPERPOWER</small><p>{identity.superpower}</p></article><article><small>CONTENT TERRITORY</small><p>{identity.territory.join(" × ")}</p></article></div><blockquote><small>YOU COULD BECOME KNOWN FOR…</small><p>“{identity.positioning}”</p></blockquote><div className="universe-identity-pillars">{identity.pillars.map((pillar,index)=><span key={pillar}><b>{index+1}</b>{pillar}</span>)}</div><aside><small>YOUR BRAIN NOTICED SOMETHING</small><p>{identity.insight}</p></aside></section></header>;
}
