import {useEffect,type ReactNode} from "react";
import {useQuery} from "convex/react";
import {api} from "../../../convex/_generated/api";
import {navigateTo} from "../../routing/routes";
import {track} from "../../lib/analytics";
import {PublicSiteLayout} from "../site/PublicSiteLayout";
import type {SiteSession} from "../site/SiteHeader";
import {CreatorTypeCard} from "../creatorType/CreatorTypeCard";
import {isCreatorTypeName,type CreatorTypeResult} from "../../features/creatorType/creatorTypes";

export function PublicUniversePage({shareId,session}:{shareId:string;session:SiteSession}){
 const universe=useQuery(api.universeShares.getPublic,{slug:shareId});
 useEffect(()=>{if(!universe)return;track("public_universe_viewed",{referral_share_id:shareId,source:"public_universe"});if(universe.creatorType)track("creator_type_public_viewed",{referral_share_id:shareId,creator_type:universe.creatorType.creatorType});document.title=`${universe.displayName?`${universe.displayName} is`:`Meet`} ${universe.creatorType?.creatorType??universe.archetype}. What’s your Content Universe?`;const description=universe.creatorType?`${universe.creatorType.creatorType}. ${universe.creatorType.signatureStrength} Find your content creator type.`:`${universe.superpower} Build your own Content Universe in four questions.`;[{name:"description",value:description},{name:"og:title",value:document.title,property:true},{name:"og:description",value:description,property:true},{name:"og:type",value:"profile",property:true},{name:"og:url",value:location.href,property:true},{name:"twitter:card",value:"summary_large_image"}].forEach(({name,value,property})=>{const attr=property?"property":"name";let node=document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${name}"]`);if(!node){node=document.createElement("meta");node.setAttribute(attr,name);document.head.append(node)}node.content=value})},[shareId,universe]);
 const buildMine=()=>{sessionStorage.setItem("suchamojo:referral-share-id",shareId);track("build_yours_from_shared_page_clicked",{referral_share_id:shareId,source:"public_universe"});if(universe?.creatorType)track("creator_type_build_yours_clicked",{referral_share_id:shareId,creator_type:universe.creatorType.creatorType});sessionStorage.setItem("suchamojo:return-to","/universe/start");navigateTo("/signup")};
 let content:ReactNode;
 if(universe===undefined)content=<main className="public-universe-state">Opening this Content Universe…</main>;
 else if(universe===null)content=<main className="public-universe-state"><h1>This Content Universe is not public.</h1><button onClick={()=>navigateTo("/signup")}>BUILD MINE →</button></main>;
 else {const creatorResult=universe.creatorType&&isCreatorTypeName(universe.creatorType.creatorType)?universe.creatorType as CreatorTypeResult:undefined;content=<main className="public-universe-page">{creatorResult?<section className="public-creator-type"><header><small>{universe.displayName?`${universe.displayName.toUpperCase()} IS:`:"THIS CREATOR IS:"}</small><h1>{creatorResult.creatorType}</h1></header><div className="public-creator-card"><div><CreatorTypeCard result={creatorResult} format="post"/></div></div><footer><small>WHAT KIND OF CONTENT CREATOR ARE YOU?</small><p>Build your Content Universe and find the pattern in how you create.</p><button onClick={buildMine}>BUILD YOUR CONTENT UNIVERSE →</button></footer></section>:null}<article><small>{universe.displayName?`${universe.displayName.toUpperCase()}’S CONTENT UNIVERSE`:"A CONTENT UNIVERSE"}</small><h1>{universe.archetype}</h1><section><div><span>SUPERPOWER</span><p>{universe.superpower}</p></div><div><span>CONTENT TERRITORY</span><p>{universe.territory.join(" × ")}</p></div></section><blockquote><span>YOU COULD BECOME KNOWN FOR…</span><p>“{universe.positioning}”</p></blockquote><ol>{universe.pillars.map(pillar=><li key={pillar}>{pillar}</li>)}</ol><aside><span>THEIR BRAIN NOTICED</span><p>{universe.insight}</p></aside></article><footer><small>{creatorResult?"THIS IS THEIR CREATOR TYPE + CONTENT UNIVERSE.":"THIS IS THEIR CONTENT UNIVERSE."}</small><h2>{creatorResult?"What kind of creator are you?":"What’s yours?"}</h2><p>Answer four questions. See what your brain finds.</p><button onClick={buildMine}>BUILD MINE →</button></footer></main>}
 return <PublicSiteLayout session={session}>{content}</PublicSiteLayout>;
}
