import {useEffect} from "react";
import {articles,articleBySlug} from "../../content/articles";
import {siteLinks} from "../../config/siteLinks";
import {navigateTo} from "../../routing/routes";
import {PublicSiteLayout} from "../site/PublicSiteLayout";
import type {SiteSession} from "../site/SiteHeader";

const pageMeta:Record<string,[string,string]>={
 "/resources":["Personal branding and content resources","Practical guides on content, positioning, storytelling, AI and building a body of work."],
 "/blog":["Everything Content blog","Ideas on personal branding, content, AI, creators and building a body of work."],
 "/guides/content-universe":["Build your Content Universe","Map your character, strengths, interests, stories and expertise into a useful content direction."],
 "/guides/personal-branding":["A practical personal branding guide","Build a personal brand from what you already know—without becoming performative."],
 "/privacy":["Privacy policy","How Everything Content handles account details, Content Universe answers and product usage data."],
 "/terms":["Terms of use","The V1 terms for using Everything Content and reviewing AI-generated outputs."],
 "/contact":["Talk to a human","Ways to contact Everything Content about the product, community, consulting or data."],
};

function Metadata({title,description,path,type="website"}:{title:string;description:string;path:string;type?:string}){useEffect(()=>{document.title=`${title} — Everything Content`;const canonical=new URL(path,siteLinks.siteUrl).href;const values:Record<string,string>={description,"og:title":title,"og:description":description,"og:type":type,"og:url":canonical,"og:image":new URL("/content-brain-hero.png",siteLinks.siteUrl).href,"twitter:card":"summary_large_image","twitter:title":title,"twitter:description":description};for(const [name,content] of Object.entries(values)){const attr=name.startsWith("og:")?"property":"name";let node=document.head.querySelector<HTMLMetaElement>(`meta[${attr}="${name}"]`);if(!node){node=document.createElement("meta");node.setAttribute(attr,name);document.head.append(node)}node.content=content}let link=document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!link){link=document.createElement("link");link.rel="canonical";document.head.append(link)}link.href=canonical;let schema=document.head.querySelector<HTMLScriptElement>('script[data-page-schema]');if(!schema){schema=document.createElement("script");schema.type="application/ld+json";schema.dataset.pageSchema="true";document.head.append(schema)}schema.text=JSON.stringify(type==="article"?{"@context":"https://schema.org","@graph":[{"@type":"Article",headline:title,description,url:canonical,publisher:{"@type":"Organization",name:"Everything Content"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Everything Content",item:siteLinks.siteUrl},{"@type":"ListItem",position:2,name:"Blog",item:new URL("/blog",siteLinks.siteUrl).href},{"@type":"ListItem",position:3,name:title,item:canonical}]}]}:{"@context":"https://schema.org","@type":"WebPage",name:title,description,url:canonical});return()=>{}},[title,description,path,type]);return null}

const guestSession:SiteSession={authenticated:false,hasUniverse:false};
let activeSession=guestSession;
function Shell({children,title,description,path,type}:{children:React.ReactNode;title:string;description:string;path:string;type?:string}){return <PublicSiteLayout session={activeSession} className="public-editorial-page"><Metadata title={title} description={description} path={path} type={type}/>{children}</PublicSiteLayout>}
function PageIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <header className="public-page-intro"><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>}
function Cta(){return <aside className="public-inline-cta"><span>YOUR BEST CONTENT STARTS BEFORE THE CONTENT.</span><h2>Build your Content Universe.</h2><button onClick={()=>navigateTo("/signup")}>Build my Content Universe →</button></aside>}

function BlogIndex(){const [title,description]=pageMeta["/blog"];return <Shell title={title} description={description} path="/blog"><PageIntro eyebrow="EVERYTHING CONTENT" title="Ideas on personal branding, content, AI, creators and building a body of work." copy="Useful thinking for people with more to say than they know how to organise."/><section className="article-index">{articles.map(article=><button key={article.slug} onClick={()=>navigateTo(`/blog/${article.slug}`)}><small>{article.category} · {article.readingTime}</small><h2>{article.title}</h2><p>{article.summary}</p><span>{article.published} →</span></button>)}</section></Shell>}
function ArticlePage({slug}:{slug:string}){const article=articleBySlug(slug);if(!article)return <NotFound/>;return <Shell title={article.title} description={article.summary} path={`/blog/${slug}`} type="article"><article className="public-article"><header><span>{article.category} / {article.readingTime}</span><h1>{article.title}</h1><p>{article.summary}</p><small>{article.published}</small></header>{article.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.bullets?<ul>{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>:null}</section>)}<Cta/></article></Shell>}
function Resources(){const [title,description]=pageMeta["/resources"];const categories=["PERSONAL BRANDING","CONTENT SYSTEMS","STORYTELLING","AI + CONTENT","CONTENT UNIVERSE","CREATOR ECONOMY"];return <Shell title={title} description={description} path="/resources"><PageIntro eyebrow="RESOURCES" title="Resources for building a personal brand from what you already know." copy={description}/><section className="resource-grid">{categories.map(category=><article key={category}><small>{category}</small>{articles.filter(article=>article.category===category).slice(0,2).map(article=><button key={article.slug} onClick={()=>navigateTo(`/blog/${article.slug}`)}>{article.title} →</button>)}{!articles.some(article=>article.category===category)?<span>New guide coming soon.</span>:null}</article>)}</section></Shell>}
function Guide({kind}:{kind:"universe"|"brand"}){const universe=kind==="universe";const path=universe?"/guides/content-universe":"/guides/personal-branding";const [title,description]=pageMeta[path];const items=universe?["Character","Own Gifts","Radiance","Expression","Stories","Expertise","Point of view","Audience","Proof","References"]:["Know what you want to be known for","Understand what makes your perspective different","Find your stories","Build sustainable content pillars","Choose your natural expression","Build a system for research and ideas","Create consistently from context"];return <Shell title={title} description={description} path={path}><PageIntro eyebrow={universe?"CONTENT UNIVERSE GUIDE":"PERSONAL BRANDING GUIDE"} title={universe?"Build your Content Universe.":"Build a personal brand from what you already know."} copy={universe?"Your best content starts before the content.":"A useful personal brand begins with identity, expertise and experience—not pressure to post."}/><section className="guide-list">{items.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><h2>{item}</h2><p>{universe?(index<4?"One of the four starting signals that helps your Content Brain understand what only you can create.":"A deeper layer that makes your direction more specific, credible and useful."):"A practical step for building recognisable work without performing a version of yourself."}</p></article>)}</section><Cta/></Shell>}
function Privacy(){const [title,description]=pageMeta["/privacy"];return <Shell title={title} description={description} path="/privacy"><PageIntro eyebrow="PRIVACY" title="Privacy policy" copy="How Everything Content handles the information used to build your Content Brain."/><section className="policy-copy"><h2>Information you provide</h2><p>This may include your name and account details, Content Universe answers, creator-profile links, ideas, scripts, notes, saved references and anything else you add to the product.</p><h2>How we use it</h2><p>We use this information to create and secure your account, save your progress, run the workspace and generate outputs shaped by the context you provide.</p><h2>AI + your data</h2><p>Content Brain may send relevant user context to Google Gemini, the AI provider currently configured in the product, so it can generate personalised outputs.</p><p>AI can make mistakes. The product is designed not to invent personal facts, but generated text can still be wrong, incomplete or misleading. Review generated content before you publish or rely on it.</p><h2>How data is stored</h2><p>Convex provides account services and database storage for account-linked information, Content Universe answers and workspace content. Some progress and preferences are also stored in your browser on the device you use.</p><h2>Cookies and analytics</h2><p>We use PostHog to understand product usage and improve the experience. Authentication, hosting and other service providers may also use necessary cookies or process basic request and error logs to operate their services.</p><h2>Deleting or resetting data</h2><p>You can reset Content Universe progress and clear local workspace data from the product. This removes browser-stored data on that device. Full account and server-side deletion is not currently self-service.</p><h2>Third-party service providers</h2><p>The product relies on Convex for account services and data storage, Google Gemini for AI processing, Vercel for website hosting, and external community and booking services when you choose those links. Their own terms and privacy practices also apply.</p><h2>Privacy requests</h2><p>Email <a href={siteLinks.contact}>{siteLinks.contactEmail}</a> for privacy or data requests.</p></section></Shell>}
function Terms(){const [title,description]=pageMeta["/terms"];return <Shell title={title} description={description} path="/terms"><PageIntro eyebrow="TERMS" title="Terms of use" copy="The basic conditions for using Everything Content."/><section className="policy-copy"><h2>Using the product</h2><p>Use the service lawfully, follow these terms and keep your account access secure. You may not disrupt the service or try to access another person's account or workspace.</p><h2>User-provided content</h2><p>You remain responsible for content you submit, save or upload. You must have the rights and permission needed to use it.</p><h2>AI output disclaimer</h2><p>AI-generated suggestions may be incorrect, incomplete or unsuitable. You remain responsible for reviewing them and deciding what you publish.</p><h2>Intellectual property</h2><p>You keep your rights in content you provide. Everything Content keeps its rights in the product, interface, brand and original site material. Using the product does not transfer those rights.</p><h2>Acceptable use</h2><p>Do not use the product for unlawful, harmful, deceptive or abusive activity, to violate another person's rights, or to interfere with the product's operation.</p><h2>Third-party services</h2><p>The product relies on services including Convex, Google Gemini, Vercel, and external community and booking providers. Their own terms may apply when you use them.</p><h2>Service availability</h2><p>The service may change, pause or contain errors. We cannot promise that every feature or generated result will always be available.</p><h2>Account termination</h2><p>Access may be suspended or ended when these terms are broken, the product is misused, or operating the service creates legal or security risk.</p><h2>Limitations</h2><p>Use the product and its outputs with your own judgement. To the extent allowed by law, Everything Content is not responsible for decisions, publications or losses based on generated output or unavailable service.</p><h2>Changes to these terms</h2><p>These terms may change as the product develops. Material changes should be shown with an updated effective date.</p></section></Shell>}
const contactLinkProps={target:"_blank",rel:"noopener noreferrer"} as const;
function Contact(){const [title,description]=pageMeta["/contact"];return <Shell title={title} description={description} path="/contact"><PageIntro eyebrow="CONTACT" title="Talk to a human." copy="Choose what you want to talk about."/><section className="contact-options"><a href={siteLinks.contact}>Product question <span>{siteLinks.contactEmail} ↗</span></a><a href={siteLinks.community} {...contactLinkProps}>Community <span>Join the community ↗</span></a><a href={siteLinks.topmate} {...contactLinkProps}>Work with me <span>Book time ↗</span></a><a href={siteLinks.contact}>Privacy / data request <span>{siteLinks.contactEmail} ↗</span></a><a href={siteLinks.contact}>General <span>{siteLinks.contactEmail} ↗</span></a></section></Shell>}
function NotFound(){return <Shell title="Page not found" description="This page does not exist." path={location.pathname}><PageIntro eyebrow="404" title="That page isn't here." copy="Return to Everything Content or explore the resource library."/><button className="public-back-home" onClick={()=>navigateTo("/")}>Back home →</button></Shell>}

export function isPublicContentPath(path:string){return path==="/resources"||path==="/blog"||path.startsWith("/blog/")||path==="/guides/content-universe"||path==="/guides/personal-branding"||path==="/ai-data"||path==="/privacy"||path==="/terms"||path==="/contact"}
export function PublicPage({path,session=guestSession}:{path:string;session?:SiteSession}){activeSession=session;if(path==="/resources")return <Resources/>;if(path==="/blog")return <BlogIndex/>;if(path.startsWith("/blog/"))return <ArticlePage slug={path.slice(6)}/>;if(path==="/guides/content-universe")return <Guide kind="universe"/>;if(path==="/guides/personal-branding")return <Guide kind="brand"/>;if(path==="/ai-data"||path==="/privacy")return <Privacy/>;if(path==="/terms")return <Terms/>;if(path==="/contact")return <Contact/>;return <NotFound/>}
