import {useState,type ReactNode} from "react";
import type {ContentUniverse} from "../lib/recommendation";
import {UniverseIdentityArtifact} from "./universe/UniverseIdentityArtifact";

const Tags=({items}:{items:string[]})=><div className="cu-doc-tags">{items.map((item,index)=><span key={`${item}-${index}`}>{item}</span>)}</div>;

export function UniverseView({universe,onSaveIdea,onCreate,onCreateShare,onNeedAccount,shareStudio}:{universe:ContentUniverse;onSaveIdea?:(idea:string)=>void;onCreate?:()=>void;onCreateShare?:(input:{includeName:boolean;archetype:string;superpower:string;territory:string[];positioning:string;pillars:string[];insight:string})=>Promise<{slug:string}>;onNeedAccount?:()=>void;onTeach?:()=>void;shareStudio?:ReactNode}) {
 const [saved,setSaved]=useState<string[]>([]);
 const save=(idea:string)=>{setSaved((current)=>current.includes(idea)?current:[...current,idea]);onSaveIdea?.(idea)};
 const sections=[["character","Brand character"],["gifts","Own gifts"],["radiance","Radiance"],["expression","Expression"],["positioning","Positioning"],["pillars","Content pillars"],["stories","Story bank"],["ideas","Idea universe"]];
 return <article className="universe-result universe-result--document">
  <UniverseIdentityArtifact universe={universe} onCreate={onCreate} onCreateShare={onCreateShare} onNeedAccount={onNeedAccount}/>
  {shareStudio}
  <nav className="cu-doc-nav" aria-label="Content Universe sections">{sections.map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
  <div className="cu-doc-body">
   <section id="character" className="cu-doc-section cu-doc-character"><header><small>BRAND CHARACTER</small><h2>Keywords + narrative</h2></header><div className="cu-doc-subsection"><h3>Keywords</h3><Tags items={[...universe.character.identitySignals,...universe.character.characterTraits]}/></div><div className="cu-doc-subsection cu-doc-narrative"><h3>Narrative</h3><p>{universe.character.summary}</p><aside><small>CORE MOTIVE</small><strong>{universe.character.coreMotive}</strong></aside></div></section>
   <section id="gifts" className="cu-doc-section"><header><small>OWN GIFTS</small><h2>Zone of genius</h2></header><div className="cu-doc-columns"><div><h3>People may come to you for</h3><ul>{universe.gifts.naturalStrengths.map(item=><li key={item}>{item}</li>)}</ul></div><aside className="cu-doc-callout"><small>YOUR SUPERPOWER</small><strong>{universe.gifts.superpower}</strong></aside></div></section>
   <section id="radiance" className="cu-doc-section"><header><small>RADIANCE</small><h2>Core themes</h2></header><Tags items={universe.radiance.topics}/>{universe.radiance.interestingIntersections.length?<div className="cu-doc-connections">{universe.radiance.interestingIntersections.map(item=><article key={item.title}><small>INTERESTING CONNECTION</small><h3>{item.title}</h3><p>{item.insight}</p></article>)}</div>:null}</section>
   <section id="expression" className="cu-doc-section"><header><small>EXPRESSION</small><h2>How your ideas come alive</h2></header><p className="cu-doc-lead">{universe.expression.profile}</p><div className="cu-doc-columns"><div><h3>Strongest formats</h3><Tags items={universe.expression.bestFormats}/></div>{universe.expression.lessNaturalFormats.length?<div><h3>Less natural for now</h3><Tags items={universe.expression.lessNaturalFormats}/><small className="cu-doc-caveat">A recommendation, not a fixed rule.</small></div>:null}</div></section>
   <section id="positioning" className="cu-doc-section cu-doc-positioning"><small>POSITIONING</small><h2>{universe.territory.positioning}</h2><strong>{universe.territory.archetype}</strong><div>{universe.territory.territories.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></section>
   <section id="pillars" className="cu-doc-section"><header><small>STRATEGIC CONTENT PILLARS</small><h2>What you can keep returning to</h2></header><div className="cu-doc-accordion">{universe.contentPillars.map((pillar,index)=><details open={index===0} key={pillar.title}><summary><span>{String(index+1).padStart(2,"0")}</span><h3>{pillar.title}</h3><b>+</b></summary><div><p>{pillar.why}</p><Tags items={pillar.topics}/></div></details>)}</div></section>
   <section id="stories" className="cu-doc-section"><header><small>CORE STORY ARCS</small><h2>Stories only you can tell</h2></header><p className="cu-doc-note">Every story below keeps a visible line back to your own words.</p><div className="cu-doc-accordion">{universe.storyBank.map((story,index)=><details key={`${story.title}-${index}`}><summary><span>ARC {index+1}</span><h3>{story.title}</h3><b>+</b></summary><div><small>YOUR SOURCE</small><blockquote>“{story.source}”</blockquote><small>POSSIBLE LESSON</small><p>{story.lesson}</p><button onClick={()=>save(story.potentialHook)}>{saved.includes(story.potentialHook)?"IDEA SAVED ✓":"SAVE THIS CONTENT IDEA →"}</button></div></details>)}</div></section>
   <section id="ideas" className="cu-doc-section"><header><small>IDEA UNIVERSE</small><h2>Starting points, grouped by pillar</h2></header><div className="cu-doc-idea-groups">{universe.ideaUniverse.map((group,index)=><details open={index===0} key={group.pillar}><summary><h3>{group.pillar}</h3><b>{group.ideas.length} ideas</b></summary><div>{group.ideas.map(idea=><button key={idea} onClick={()=>save(idea)}><span>{idea}</span><b>{saved.includes(idea)?"SAVED ✓":"SAVE +"}</b></button>)}</div></details>)}</div></section>
   <section className="cu-doc-ready"><small>YOUR CONTENT UNIVERSE IS READY</small><h2>Start creating now.<br/>Add detail when it becomes useful.</h2><button onClick={onCreate}>CREATE WITH MY BRAIN →</button></section>
  </div>
 </article>;
}
