import {useEffect,useRef,useState} from "react";import type {ContentUniverse} from "../../lib/recommendation";import {toShareableUniverse} from "../../lib/shareableUniverse";import {track} from "../../lib/analytics";import {downloadRenderedCard,renderShareCardPng} from "../../lib/sharePackExport";import {classifyCreatorTypeFallback,creatorTypeDefinitions,creatorTypeNames,type CreatorTypeResult} from "../../features/creatorType/creatorTypes";import {shareFormats,type ShareFormat} from "../share/storyCardData";import {CreatorTypeCard} from "./CreatorTypeCard";
type ShareInput=ReturnType<typeof toShareableUniverse>&{includeName:boolean;creatorType?:CreatorTypeResult};
export function CreatorTypeExperience({universe,classify,onCreateShare,onNeedAccount}:{universe:ContentUniverse;classify?:(universeId?:string)=>Promise<CreatorTypeResult>;onCreateShare?:(input:ShareInput)=>Promise<{slug:string}>;onNeedAccount?:()=>void}){const [result,setResult]=useState<CreatorTypeResult>();const [format,setFormat]=useState<ShareFormat>("story");const [shareUrl,setShareUrl]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [showAll,setShowAll]=useState(false);const exportRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;(async()=>{let value:CreatorTypeResult;try{value=classify?await classify():classifyCreatorTypeFallback(universe)}catch{value=classifyCreatorTypeFallback(universe)}if(active){setResult(value);track("creator_type_generated",{creator_type:value.creatorType})}})();return()=>{active=false}},[classify,universe]);
 const ensureUrl=async()=>{if(shareUrl)return shareUrl;if(!result)throw new Error("Creator type is still loading.");if(!onCreateShare){onNeedAccount?.();throw new Error("Create an account to share your creator type.")}const {slug}=await onCreateShare({...toShareableUniverse(universe),includeName:true,creatorType:result});const url=new URL(`/u/${slug}`,location.origin).href;setShareUrl(url);return url};
 const render=async()=>{if(!result||!exportRef.current)throw new Error("Creator card is still loading.");return renderShareCardPng(exportRef.current,format,`my-creator-type-${format}.png`)};
 const download=async()=>{setBusy(true);try{const image=await render();downloadRenderedCard(image.dataUrl,image.file.name);track("creator_type_downloaded",{creator_type:result?.creatorType??null,format});setNotice(`${shareFormats[format].label} card downloaded.`)}catch(error){setNotice((error as Error).message)}finally{setBusy(false)}};
 const share=async()=>{setBusy(true);try{const url=await ensureUrl();const image=await render();const text=`Apparently I’m ${result?.creatorType.replace("THE ","The ")}\n\nWhich is annoyingly accurate.\n\nWhat’s your content creator type?`;if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[image.file]})))await navigator.share({title:"What kind of content creator are you?",text,url,files:[image.file]});else{downloadRenderedCard(image.dataUrl,image.file.name);await navigator.clipboard.writeText(`${text}\n${url}`);setNotice("Card downloaded and caption copied.")}track("creator_type_shared",{creator_type:result?.creatorType??null,format,share_id:url.split("/").pop()??null})}catch(error){if((error as Error).name!=="AbortError")setNotice((error as Error).message)}finally{setBusy(false)}};
 const copyLink=async()=>{try{const url=await ensureUrl();await navigator.clipboard.writeText(url);setNotice("Public link copied.")}catch(error){setNotice((error as Error).message)}};
 if(!result)return <section className="creator-type-loading"><span>YOUR CREATOR TYPE</span><h2>Finding the pattern in how you create…</h2></section>;
 return <section className="creator-type-experience"><header><span>YOUR CREATOR TYPE</span><h2>What kind of content creator are you?</h2><p>{result.whyYou}</p></header><div className="creator-type-format"><small>FORMAT</small>{(Object.keys(shareFormats) as ShareFormat[]).map(item=><button className={format===item?"is-active":""} onClick={()=>setFormat(item)} key={item}>{shareFormats[item].label}</button>)}</div><div className={`creator-type-preview creator-type-preview--${format}`}><div><CreatorTypeCard result={result} format={format}/></div></div><aside className="creator-type-result"><div><small>WATCH OUT FOR</small><p>{result.watchOutFor}</p></div><div><small>YOUR SIGNATURE STRENGTH</small><p>{result.signatureStrength}</p></div></aside><div className="creator-type-actions"><button className="is-primary" onClick={()=>void share()} disabled={busy}>{busy?"Making card…":"Share this →"}</button><button onClick={()=>void download()} disabled={busy}>Download</button><button onClick={()=>void copyLink()}>Copy link</button><button onClick={()=>setShowAll(value=>!value)}>{showAll?"Hide creator types":"See all creator types"}</button></div>{notice?<p className="creator-type-notice" role="status">{notice}</p>:null}{showAll?<section className="creator-type-grid"><header><small>THE TEN CREATOR TYPES</small><h3>Compare notes with your people.</h3></header><div>{creatorTypeNames.map(name=><article style={{"--creator-accent":creatorTypeDefinitions[name].accent} as React.CSSProperties} key={name}><i/><h4>{name}</h4><p>{creatorTypeDefinitions[name].short}</p></article>)}</div></section>:null}<div className="creator-type-export"><div ref={exportRef}><CreatorTypeCard result={result} format={format}/></div></div></section>}
