import {cleanup,render,screen} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";import App from "./App";
beforeEach(()=>{localStorage.clear();history.replaceState({},"","/");vi.stubGlobal("scrollTo",vi.fn());vi.stubGlobal("matchMedia",vi.fn(()=>({matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()})))});afterEach(cleanup);
describe("four-question Content Universe",()=>{
 it("starts signup before the four questions for a new visitor",async()=>{const user=userEvent.setup();const requestAuth=vi.fn();render(<App authenticated={false} onRequestAuth={requestAuth}/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);expect(requestAuth).toHaveBeenCalledOnce();expect(sessionStorage.getItem("suchamojo:return-to")).toBe("/universe/start")});
 it("requires each text answer and allows going backwards to edit",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);const continueButton=screen.getByRole("button",{name:"Continue"});expect(continueButton).toBeDisabled();await user.type(screen.getByRole("textbox",{name:"Your answer"}),"Curious, direct, and shaped by moving cities. 🧠");expect(continueButton).toBeEnabled();await user.click(continueButton);expect(screen.getByText("02 / 04")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:/back/i}));expect(screen.getByDisplayValue(/moving cities/)).toBeInTheDocument();expect(JSON.parse(localStorage.getItem("suchamojo:content-universe:v1")??"{}").answers.character).toMatch(/🧠/u)});
 it("moves an authenticated user directly through all four questions",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);for(const answer of ["My story","My gifts","My interests"]){await user.type(screen.getByRole("textbox",{name:"Your answer"}),answer);await user.click(screen.getByRole("button",{name:"Continue"}))}expect(screen.queryByRole("dialog")).not.toBeInTheDocument();expect(screen.getByText("04 / 04")).toBeInTheDocument()});
 it("saves a completed step only when Continue is clicked",async()=>{const user=userEvent.setup();const saveAnswer=vi.fn(async()=>"answer-id");render(<App persistence={{buildUniverse:vi.fn(async()=>{throw new Error("not used")}),saveAnswer}}/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);await user.type(screen.getByRole("textbox",{name:"Your answer"}),"I am curious and direct.");expect(saveAnswer).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Continue"}));expect(saveAnswer).toHaveBeenCalledWith({questionKey:"character",module:"activation",answer:"I am curious and direct.",skipped:false});expect(screen.getByText("02 / 04")).toBeInTheDocument()});
 it("offers a creator example and starter lines without overwriting the answer",async()=>{const user=userEvent.setup();render(<App/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);await user.click(screen.getByRole("button",{name:/see camasou/i}));expect(screen.getByText(/started as a journalist/i)).toBeInTheDocument();await user.type(screen.getByRole("textbox",{name:"Your answer"}),"My own beginning.");await user.click(screen.getByRole("button",{name:/a turning point was/i}));expect((screen.getByRole("textbox",{name:"Your answer"}) as HTMLTextAreaElement).value).toContain("My own beginning.\nA turning point was…")});
 it("shows the loading brain while the Content Universe is being generated",async()=>{const user=userEvent.setup();const buildUniverse=vi.fn(()=>new Promise<never>(()=>{}));render(<App persistence={{buildUniverse}}/>);await user.click(screen.getAllByRole("button",{name:/build my content universe/i})[0]);for(const answer of ["My story","My gifts","My interests"]){await user.type(screen.getByRole("textbox"),answer);await user.click(screen.getByRole("button",{name:"Continue"}))}await user.click(screen.getByRole("button",{name:/talking to camera/i}));await user.click(screen.getByRole("button",{name:/build my universe/i}));expect(buildUniverse).toHaveBeenCalledOnce();expect(screen.getByRole("heading",{name:/becoming a point of view/i})).toBeInTheDocument();expect(screen.getByText(/keeps the next idea from becoming more AI slop/i)).toBeInTheDocument()});
 it("shows the full Universe without a reveal screen and routes into brain training",async()=>{const user=userEvent.setup();localStorage.setItem("suchamojo:content-universe:v1",JSON.stringify({view:"preview",step:0,answers:{},completedModules:[],universe:{character:{summary:"A grounded creator",identitySignals:[],characterTraits:[],coreMotive:"Make useful things"},gifts:{naturalStrengths:[],superpower:"Finding clear angles"},radiance:{topics:[],interestingIntersections:[]},expression:{profile:"Clear teaching",bestFormats:[],lessNaturalFormats:[]},territory:{archetype:"The Guide",positioning:"Help experts explain what they know.",territories:[{title:"Useful expertise",description:"Make knowledge easier to use."}]},contentPillars:[],storyBank:[],ideaUniverse:[]}}));history.replaceState({},"","/universe/preview");render(<App/>);expect(screen.queryByRole("button",{name:/reveal/i})).not.toBeInTheDocument();expect(screen.getByText(/a grounded creator/i)).toBeInTheDocument();expect(screen.getByRole("heading",{name:"The Guide"})).toBeInTheDocument();expect(screen.getByRole("button",{name:/teach my brain more/i})).toBeInTheDocument();await user.click(screen.getByRole("button",{name:/teach my brain more/i}));expect(location.pathname).toBe("/app/train")});
 it("restores a module route after refresh and continues at the first unanswered question",()=>{localStorage.setItem("suchamojo:content-universe:v1",JSON.stringify({view:"hub",step:0,answers:{proof_results:"Built a useful company"},completedModules:[]}));history.replaceState({},"","/universe/proof");render(<App/>);expect(screen.getByRole("heading",{name:/numbers, results/i})).toBeInTheDocument();expect(screen.getByRole("button",{name:/question 1, answered/i})).toBeInTheDocument()});
});
