import {useEffect,useState} from "react";
import {PublicSiteLayout} from "./components/site/PublicSiteLayout";
import {HomePage} from "./components/HomePage";
import {ModuleExperience} from "./components/universe/ModuleExperience";
import {StageInsight} from "./components/universe/StageInsight";
import {UniverseHub} from "./components/universe/UniverseHub";
import {NextSteps} from "./components/universe/NextSteps";
import type {CreatorProfile} from "./components/universe/ProfileSources";
import type {UniverseMode} from "./components/universe/UniverseStartChoice";
import {FourRambleFlow} from "./components/universe/FourRambleFlow";
import {BrainLoading} from "./components/universe/BrainLoading";
import {UniverseView} from "./components/UniverseView";
import {YapIdeas} from "./components/yap/YapIdeas";
import {StoryShareStudio} from "./components/share/StoryShareStudio";
import {CreatorTypeExperience} from "./components/creatorType/CreatorTypeExperience";
import type {CreatorTypeResult} from "./features/creatorType/creatorTypes";
import {universeQuestions} from "./data/universeQuestions";
import {moduleForSlug,moduleSlugs,questionsForModule,type ModuleSlug} from "./data/universeModules";
import {generateUniverse,type ContentUniverse,type UniverseAnswers} from "./lib/recommendation";
import {track} from "./lib/analytics";
import {referralProperties} from "./lib/referral";

type View="landing"|"sources"|"hub"|"interview"|"insight"|"building"|"preview"|"universe"|"next";
interface SavedState { view:View;step:number;answers:UniverseAnswers;activeModule?:ModuleSlug;completedModules:ModuleSlug[];mode?:UniverseMode;universe?:ContentUniverse;universeId?:string;insightStage?:number;creatorProfile?:CreatorProfile; }
interface UserProfile { id:string;name:string|null;email:string|null;phone?:string|null; }
interface SavedUniverse { id:string;answers:UniverseAnswers;universe:ContentUniverse; }
interface ShareInput {universeId:string;includeName:boolean;archetype:string;superpower:string;territory:string[];positioning:string;pillars:string[];insight:string;creatorType?:CreatorTypeResult}
export interface ContentPersistence { buildUniverse:(input:{answers:UniverseAnswers})=>Promise<{id:string;universe:ContentUniverse;cached:boolean}>;classifyCreatorType?:(universeId:string)=>Promise<CreatorTypeResult>;saveIdea?:(input:{universeId:string;text:string})=>Promise<string>;saveCreatorProfile?:(profile:CreatorProfile)=>Promise<string>;saveAnswer?:(input:{questionKey:string;module:string;answer:string;skipped:boolean})=>Promise<string>;createUniverseShare?:(input:ShareInput)=>Promise<{slug:string}>;yapEnabled?:boolean; }
const STORAGE_KEY="suchamojo:content-universe:v1";
function locationState(path=location.pathname):Pick<SavedState,"view"|"activeModule"> { if(path==="/")return {view:"landing"};if(path==="/universe/start")return {view:"sources"};if(path==="/universe")return {view:"hub"};if(path==="/universe/preview"||path==="/universe/building"||path==="/universe/result")return {view:"universe"};if(path==="/brain"||path==="/next")return {view:"next"};const match=path.match(/^\/universe\/([^/]+)(?:\/result)?$/);const module=moduleForSlug(match?.[1]);if(module)return {view:path.endsWith("/result")?"insight":"interview",activeModule:module.slug};return {view:"landing"}; }
function pathFor(state:SavedState){if(state.view==="landing")return "/";if(state.view==="sources")return "/universe/start";if(state.view==="hub")return "/universe";if(state.view==="interview")return `/universe/${state.activeModule}`;if(state.view==="insight")return `/universe/${state.activeModule}/result`;if(state.view==="building")return "/universe/building";if(state.view==="preview")return "/universe/preview";if(state.view==="universe")return "/universe/result";return "/brain";}
function loadState():SavedState {const route=locationState();const base:SavedState={...route,step:0,answers:{},completedModules:[]};try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEY)??"null");const next=stored?{...base,...stored,...route,completedModules:stored.completedModules??[]}:base;if(next.universe&&!next.universe.character)next.universe=generateUniverse(next.answers);if(route.activeModule){const module=moduleForSlug(route.activeModule)!;if(universeQuestions[next.step]?.stage!==module.stage)next.step=universeQuestions.findIndex((question)=>question.stage===module.stage)}return next}catch{return base}}

export default function App({persistence,authenticated=true,onRequestAuth,onSignOut,profile,savedUniverse,savedCreatorProfile,savedAnswers}:{persistence?:ContentPersistence;authenticated?:boolean;onRequestAuth?:()=>void;onSignOut?:()=>void;profile?:UserProfile;savedUniverse?:SavedUniverse|null;savedCreatorProfile?:CreatorProfile|null;savedAnswers?:UniverseAnswers}) {
 const [state,setState]=useState<SavedState>(loadState);const [error,setError]=useState("");const [building,setBuilding]=useState(false);
 const save=(next:SavedState,replace=false)=>{setState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));history[replace?"replaceState":"pushState"]({},"",pathFor(next));window.scrollTo({top:0,behavior:"smooth"})};
 useEffect(()=>{const back=()=>setState((current)=>{const route=locationState();let step=current.step;if(route.activeModule){const module=moduleForSlug(route.activeModule)!;if(universeQuestions[step]?.stage!==module.stage)step=universeQuestions.findIndex((question)=>question.stage===module.stage)}return {...current,...route,step}});addEventListener("popstate",back);return()=>removeEventListener("popstate",back)},[]);
 useEffect(()=>{if(!savedUniverse||state.universe)return;const next={...state,answers:{...savedUniverse.answers,...state.answers},universe:savedUniverse.universe,universeId:savedUniverse.id};setState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))},[savedUniverse,state]);
 useEffect(()=>{if(!savedCreatorProfile||state.creatorProfile)return;setState((current)=>({...current,creatorProfile:savedCreatorProfile}))},[savedCreatorProfile,state.creatorProfile]);
 useEffect(()=>{if(!savedAnswers||!Object.keys(savedAnswers).length)return;setState((current)=>{const next={...current,answers:{...savedAnswers,...current.answers}};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next})},[savedAnswers]);
 const openModule=(slug:ModuleSlug)=>{const module=moduleForSlug(slug)!;const questions=questionsForModule(slug,state.mode??"deep");const firstUnanswered=questions.findIndex((question)=>!(state.answers[question.key]??"").trim());const offset=firstUnanswered<0?0:firstUnanswered;const firstIndex=universeQuestions.findIndex((question)=>question.stage===module.stage);save({...state,view:"interview",activeModule:slug,step:firstIndex+offset})};
 const reset=()=>{localStorage.removeItem(STORAGE_KEY);save({view:"landing",step:0,answers:{},completedModules:[]},true)};
 const siteSession={authenticated,name:profile?.name??profile?.email??undefined,hasUniverse:Boolean(savedUniverse||state.universe),onSignOut,onStartOver:reset};
 if(state.view==="landing")return <HomePage authenticated={authenticated} name={profile?.name??profile?.email??undefined} hasUniverse={Boolean(savedUniverse||state.universe)} onStart={(activeModule)=>{track("build_brain_clicked",referralProperties());if(!authenticated){sessionStorage.setItem("suchamojo:return-to","/universe/start");onRequestAuth?.();return}save({...state,view:"sources",activeModule})}}/>;
 if(state.view==="sources"&&building)return <PublicSiteLayout session={siteSession} headerMode="onboarding" showFooter={false}><BrainLoading/></PublicSiteLayout>;
 if(state.view==="sources")return <PublicSiteLayout session={siteSession} headerMode="onboarding" showFooter={false}><FourRambleFlow answers={state.answers} authenticated={authenticated} error={error} busy={building} onBack={()=>save({...state,view:"landing"})} onLogin={onRequestAuth} onChange={(key,value)=>{const next={...state,answers:{...state.answers,[key]:value}};setError("");setState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}} onSaveStep={async(step)=>{if(!persistence?.saveAnswer)return;const entries=step===0?[["character",state.answers.character??""]]:step===1?[["gifts",state.answers.gifts??""]]:step===2?[["obsessions",state.answers.obsessions??""]]:[["expressionFormats",state.answers.expressionFormats??""],["expressionNotes",state.answers.expressionNotes??""]];try{await Promise.all(entries.map(([questionKey,answer])=>persistence.saveAnswer!({questionKey,module:"activation",answer,skipped:!answer.trim()})));setError("")}catch{setError("We couldn't save that answer yet. Your words are still safe on this device.");throw new Error("Answer save failed")}}} onComplete={async()=>{if(building)return;setBuilding(true);setError("");try{const expression=[state.answers.expressionFormats,state.answers.expressionNotes].filter(Boolean).join(". ");const answers={...state.answers,expression};const built=persistence?await persistence.buildUniverse({answers}):{id:`local-${Date.now()}`,universe:generateUniverse(answers),cached:false};track("universe_generated",{cached:built.cached});save({...state,answers,view:"universe",universe:built.universe,universeId:built.id})}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't build that part of your brain yet.")}finally{setBuilding(false)}}}/></PublicSiteLayout>;
 if(state.view==="hub")return <UniverseHub mode={state.mode??"deep"} answers={state.answers} completed={state.completedModules} onOpen={openModule} onPreview={()=>state.universe?save({...state,view:"universe"}):save({...state,view:"landing"})}/>;
 if(state.view==="interview"&&state.activeModule){const module=moduleForSlug(state.activeModule)!;const questions=questionsForModule(state.activeModule,state.mode??"deep");const complete=()=>{const answered=questions.filter((question)=>(state.answers[question.key]??"").trim()).length;if(!answered){setError("Put something inside at least one file so we have something to map.");return}setError("");const completed=[...new Set([...state.completedModules,state.activeModule!])] as ModuleSlug[];save({...state,view:"insight",insightStage:module.stage,completedModules:completed})};return <ModuleExperience slug={state.activeModule} mode={state.mode??"deep"} answers={state.answers} error={error} onChange={(key,value)=>{const next={...state,answers:{...state.answers,[key]:value}};setState(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));if(persistence?.saveAnswer)void persistence.saveAnswer({questionKey:key,module:state.activeModule!,answer:value,skipped:!value.trim()})}} onBack={()=>save({...state,view:"hub"})} onComplete={complete}/>} 
 if(state.view==="insight"&&state.insightStage&&state.activeModule)return <StageInsight stage={state.insightStage} answers={state.answers} onContinue={async()=>{if(state.completedModules.length!==moduleSlugs.length){save({...state,view:"hub"});return}setError("");try{const built=persistence?await persistence.buildUniverse({answers:state.answers}):{id:`local-${Date.now()}`,universe:generateUniverse(state.answers),cached:false};save({...state,view:"universe",universe:built.universe,universeId:built.id})}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't build your Universe yet.");save({...state,view:"hub"})}}}/>;
 if(state.view==="universe"&&state.universe){const go=(path:string)=>authenticated?(()=>{history.pushState({},"",path);dispatchEvent(new PopStateEvent("popstate"))})():onRequestAuth?.();const createShare=persistence?.createUniverseShare&&state.universeId&&!state.universeId.startsWith("local-")?(input:Omit<ShareInput,"universeId">)=>persistence.createUniverseShare!({universeId:state.universeId!,...input}):undefined;const yapFromShare=(topic:string)=>{sessionStorage.setItem("suchamojo:content-brain-prefill",topic);go("/app")};const classify=persistence?.classifyCreatorType&&state.universeId&&!state.universeId.startsWith("local-")?()=>persistence.classifyCreatorType!(state.universeId!):undefined;const shareStudio=<><StoryShareStudio universe={state.universe} onCreateShare={createShare} onNeedAccount={onRequestAuth} onYap={yapFromShare}/><CreatorTypeExperience universe={state.universe} classify={classify} onCreateShare={createShare} onNeedAccount={onRequestAuth}/></>;return <PublicSiteLayout session={siteSession}><main className="editorial-page result-page"><UniverseView universe={state.universe} shareStudio={shareStudio} onCreate={()=>go("/app")} onNeedAccount={onRequestAuth} onCreateShare={createShare} onSaveIdea={async(text)=>{if(!authenticated){onRequestAuth?.();return}if(persistence?.saveIdea&&state.universeId&&!state.universeId.startsWith("local-"))await persistence.saveIdea({universeId:state.universeId,text})}}/>{persistence?.yapEnabled?<YapIdeas universe={state.universe}/>:<section className="yap-auth-gate"><span>YOU HAVE A CONTENT UNIVERSE. NOW USE IT.</span><h2>WHAT SHOULD I YAP ABOUT?</h2><p>Sign in to generate ten thoughts grounded in your Universe and keep them from repeating.</p><button onClick={onRequestAuth}>SIGN IN TO USE MY CONTENT BRAIN →</button></section>}<NextSteps onBrain={()=>go("/app")} onTrain={()=>go("/app/train")}/></main></PublicSiteLayout>}
 if(state.view==="next")return <PublicSiteLayout session={siteSession}><main className="editorial-page next-page"><NextSteps onBrain={()=>save({...state,view:"landing"})}/></main></PublicSiteLayout>;
 return <PublicSiteLayout session={siteSession}><main><h1>Your saved Universe needs its earlier answers.</h1><button onClick={reset}>Start again</button></main></PublicSiteLayout>;
}
